run_type = "transfer_learning"
device = "cuda:0"
tb_logdir = "tb_TL_denv"
json_out_config = "json_transfer_learning.json"

[parameters]
num_epochs = 100
save_every_n_epochs = 10
batch_size = 128
num_refs = 100
sample_batch_size = 100

# 使用最终清理的数据
input_model_file = "priors/reinvent.prior"
smiles_file = "data/denv_smiles_final.tsv"
output_model_file = "priors/denv_finetuned.model"
validation_smiles_file = "data/denv_smiles_final.tsv"
