run_type = "transfer_learning"
device = "cuda:0"
tb_logdir = "tb_full_denv"
json_out_config = "json_full_training.json"

[parameters]
num_epochs = 100
save_every_n_epochs = 10
batch_size = 128
num_refs = 100
sample_batch_size = 100

# 完整训练设置
input_model_file = "priors/reinvent.prior"
smiles_file = "data/denv_training_set.tsv"
output_model_file = "priors/denv_expert_model.model"
validation_smiles_file = "data/denv_training_set.tsv"

# 添加相似性配置
pairs.type = "tanimoto"
pairs.upper_threshold = 1.0
pairs.lower_threshold = 0.7
pairs.min_cardinality = 1
pairs.max_cardinality = 199
