run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_qsar_test"
json_out_config = "_qsar_test.json"

[parameters]
summary_csv_prefix = "qsar_test"
use_checkpoint = false
prior_file = "priors/denv_ultra_clean_model.model"
agent_file = "priors/denv_ultra_clean_model.model"
batch_size = 32
unique_sequences = true
randomize_smiles = true

[learning_strategy]
type = "dap"
sigma = 120
rate = 0.0001

[[stage]]
max_score = 0.7
min_steps = 10
max_steps = 50
chkpt_file = "qsar_test.chkpt"

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[stage.scoring.component.QSARScorer]
[[stage.scoring.component.QSARScorer.endpoint]]
name = "QSAR_Activity"
weight = 1.0
params.model_path = "/mnt/c/Users/ucsaheu/python_projects/DENV_Drug_Discovery/02_ML_Modeling/models/random_forest_champion.joblib"
