run_type = "transfer_learning"
device = "cuda:0"
tb_logdir = "tb_test"

[parameters]
num_epochs = 2
save_every_n_epochs = 1
batch_size = 32
num_refs = 50
sample_batch_size = 100

input_model_file = "priors/reinvent.prior"
smiles_file = "data/denv_test.tsv"
output_model_file = "priors/test_model.model"
validation_smiles_file = "data/denv_test.tsv"
